version: "3.8"

services:
  db:
    image: postgres:15
    container_name: alma_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alma
      POSTGRES_PASSWORD: alma123
      POSTGRES_DB: alma_leads
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
